version: '3.8'

services:

  db:
    image: mariadb:latest
    container_name: giftbox_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "64238:3306"

  php:
    image: canals/php:8.2
    container_name: giftbox_php
    volumes:
      - ./gift.appli/public:/var/www/html
      - ./shared/img:/var/www/html/img
      - ./gift.appli/src:/var/www/src
    ports:
      - "22004:80"
    depends_on:
      - db

  adminer:
    image: adminer:latest
    container_name: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - "19036:8080"

volumes:
  db_data: