services:
  api:
    image: canals/php:8.2
    container_name: giftbox_api
    volumes:
      - ./gift.api/public:/var/www/html
      - ./shared/img:/var/www/html/img
      - ./gift.api/src:/var/www/html/src
    ports:
      - "10023:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: giftbox_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:

      - "10024:3306"

  php:
    image: canals/php:8.2
    container_name: giftbox_php
    volumes:
      - ./gift.appli/public:/var/www/html
      - ./shared/img:/var/www/html/img
      - ./gift.appli/src:/var/www/src
    ports:
      - "10025:80"
    depends_on:
      - db


  adminer:
    image: adminer:latest
    container_name: adminer
    ports:


      - "10127:8080"
    command : php -S 0.0.0.0:8080 -t /var/www/html/

volumes:
  db_data:
